### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [qJake/SharpHue#2]
Hi qJake,

I work for Philips Hue Developer Support.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

Am not a C# developer myself,  but a quick glance at your code and it looks like it will fail after February 2016.  In your RegisterNewUser method (Configuration.cs) you will no longer be able to pass the username,  only the device type.  The randomly generated bridge username will be returned in the response,  so your code will need to be changed as such.  Apologies for the inconvenience.

Thanks
Steve

**Comment by qJake** [comment]
No worries, Steve. I appreciate you reaching out to me to let me know! I'll be sure to have this patched before that time.

**Comment by SteveyO** [comment]
Great thanks!  Yeah, not too difficult but very important.  If you could reply to this issue when done I would appreciate it, so I can mark as fixed at our end.
btw.  Just fixed a typo in the above (February 2016, not 2015 obviously).

**Comment by hosj-IO** [comment]
Jake, I send you a pull request with the proposed solution.

**Comment by qJake** [comment]
Thanks for fixing this, @hosj-IO! Closing this issue. Feel free to reopen, or open a new issue, if you find anything else.
