### ISSUE TITLE
Unathourised user when initialising with existing user

### ISSUE THREAD

**Issue by addrum** [qJake/SharpHue#6]
I'm using the below to try and initialise with an existing user

`Configuration.Initialize(Environment.MachineName);`

however I get an exception, 'Unauthorised user', am I missing something here?

In my code, I attempt to initialise with an existing user before then initialising with a new user, is this a wasted step? Do I just need to do one or the other? (I want to avoid having to press the bridge button every time the application is run)

**Comment by hosj-IO** [comment]
Normally the username should be a GUID so it can be unique. When testing the library locally and supplying an existing username(GUID), I do not receive the exception. Perhaps your Machine is longer than 40 characters. As the Hue API only accepts up to 40 characters for the username.

The steps you described sound correct. Check if user exists, otherwise create a new one. That way you only have to press the button once.

**Comment by addrum** [comment]
That makes sense. I assume when creating a new user, I store the GUID and supply that when trying to initialise for an existing user? How do I get the GUID that `Configuration.AddUser();` creates?

**Comment by hosj-IO** [comment]
With the new API from Hue, you supply a generic name(appId) MyApp#MachineName. It will generate and return you a GUID that will be your username. So if you initialize with your MachineName, a user will be generate on the bridge with the name MachineName#MachineName. 

I use the following code to pair:
`
                SharpHue.Configuration.AddUser("SiberHue");`
`                Settings.Default["Username"] = SharpHue.Configuration.Username;`
`                Settings.Default.Save();`

And on start I do the following:
`                var username = Settings.Default["Username"].ToString();`
                `Configuration.Initialize(username);`

You can take a look here: https://github.com/hosj-IO/AmbiHue

**Comment by qJake** [comment]
@hosj-IO is correct. The old way was that you got to register your own username in the system (via button press). The new way is to send your app's name when you call `AddUser()` (where you require a button press), and after the system initializes, you can read the `Username` property to determine the username you can use from that point forward (until the user de-authorizes your app or you hook up to a different hub). So once you have your system "username" you would just call `Initialize(mySavedSystemUsername)` and it should work. The user should never see or know about the username, it's an internal thing.

Closing, as I think we have sufficiently answered the question. Feel free to re-open if you're still having trouble.
